name: CI
on:
  pull_request:
    branches:
      - master

jobs:
  ci:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn_cache_dir_path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn_cache_dir_path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile --prefer-offline
      - name: Build common packages
        run: yarn build --verbose
      - name: Run type checks
        run: yarn typecheck
      - name: Run lint checks
        run: yarn lint
        env:
          NODE_ENV: 'production'
