name: CI
on:
  pull_request:
    branches:
      - master

jobs:
  ci:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20'
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Restore yarn cache
        uses: actions/cache@v2
        with:
          path: ./.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build common packages
        run: yarn build --verbose
      - name: Run type checks
        run: yarn typecheck
      - name: Run lint checks
        run: yarn lint
        env:
          NODE_ENV: 'production'
      - name: Run tests
        run: yarn test
